[package]
name = "SliceSTLfinal"
version = "0.1.0"
authors = ["sunil bhandari <sundai2005@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libmath = "0.2.1"
#nohash-hasher = "0.2.0"